import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Providers from "@/app/providers";
import {Toaster} from "@/components/ui/sonner";
import {AppSidebar} from "@/components/sidebar";
import {SidebarProvider, SidebarTrigger} from "@/components/ui/sidebar";
import {cookies, headers} from "next/headers";
import {auth} from "@/lib/auth";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {

    const cookieStore = await cookies();
    const defaultOpen = cookieStore.get("sidebar_state")?.value === "true"
    const sessData = await auth.api.getSession({
        headers: await headers(),
    });


    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >

        <Toaster richColors/>
        <Providers>
            <SidebarProvider defaultOpen={defaultOpen}>


                <AppSidebar user={sessData ? {
                    email: sessData.user.email,
                    name: sessData.user.name,
                    id: sessData.user.id,
                    image: sessData.user.image,
                } : false}/>
                <main className={"grow"}>
                    <SidebarTrigger/>
                    {children}
                </main>
            </SidebarProvider>
        </Providers>
        </body>
        </html>
    );
}
